### ISSUE TITLE
DIRECT_DML.sql fails

### ISSUE THREAD

**Issue by Sporge71** [RoelantVos/DIRECT#10]
Hi Roelant,

You appear to have a wee bug in your DIRECT_DML.sql script (line 25). The following insert fails:

```
insert into omd.AREA
select *
from (
          /* AREA_CODE, LAYER_CODE, AREA_DESCRIPTION */
    values (N'HELPER', N'Presentation', N'The Helper Area')
         , (N'PSA', N'Staging', N'The Persistent Staging Area')
...
```
The reason is that you created the table with the column order different to your insert statement. Table definition is as follows (DIRECT_DDL.sql - line 377):
```
CREATE TABLE [omd].[AREA]
(
 [AREA_CODE]        varchar(100) NOT NULL ,
 [AREA_DESCRIPTION] varchar(1000) NOT NULL ,
 [LAYER_CODE]       varchar(100) NULL ,
...
```

So you could:
1. Change your table definition to match your insert statement
2. Change your insert statement to match your table definition
3) Specify your column list in the insert statement

Ron

**Comment by RoelantVos** [comment]
Thanks for raising this (and sorry for the late reply). I have fixed this now, and it's updated for the v1.1.
