### ISSUE TITLE
Add parameter to enable limiting the load window (batching) of large loads.

### ISSUE THREAD

**Issue by scott-diprose** [RoelantVos/DIRECT#6]
When determining the load window from a high water mark. Limit the upper bounds to be the lower of the maximum available insert date time, and a set maximum period. Such as one month, or one year.
Alternately could make more complex and limit by the number of rows in a batch. Which would be even more effective.

**Comment by RoelantVos** [comment]
Going through old issues, this is now sufficiently handled via the load window (source control).
